### ISSUE TITLE
Issue: clicking the pomodoro icon does not pause/start the timer

### ISSUE THREAD

**Issue by overflowy** [kzhovn/statusbar-pomo-obsidian#34]
Action: click the pomodoro icon in the taskbar

![6uC246HMVZ](https://user-images.githubusercontent.com/98480250/156743120-375e70c8-4815-4cf4-ab57-64312fed5656.png)

Expected: pause timer if it's running, start timer if it's paused

Actual results: nothing happens

**Comment by kzhovn** [comment]
Currently that is the expected behavior, clicking the timer should either do nothing or take you to your log file if you have logging enabled.

I don't plan to implement this right now, I think it's unnecessarily confusing for most users and there are already two different ways to pause/restart the timer.

**Comment by overflowy** [comment]
To me that looked like the expected behavior, since it seems intuitive to start/pause a timer when you click it.
