### ISSUE TITLE
Feature : Create A Settings For Background Noise.

### ISSUE THREAD

**Issue by grassbl8d** [kzhovn/statusbar-pomo-obsidian#9]
# Feature Overview

Add the background noise as  a configurable setting in the settings pane similar to toggle of play sound.

**Comment by grassbl8d** [comment]
@kzhovn do you have any guide that I can follow so that I can compile the source code and test it with my running instance ? Perhaps you can sen me a link or something.

Thanks.

**Comment by kzhovn** [comment]
I've added the setting on my end, haven't pushed it yet because I'm making some changes to the code to work better with the current structure.

https://github.com/obsidianmd/obsidian-sample-plugin might be helpful to you; the tldr is that you clone the project into the `.obsidian/plugins` folder, run `npm i` and then `npm run dev`, and reload Obsidian. At that point the project should show up as just another plugin.

**Comment by grassbl8d** [comment]
Great, Thanks!
